/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

/**
 *
 * @author jessi
 */
public class UI_clienteFormaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form UI_clienteMinhaConta
     */
    public UI_clienteFormaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_chamaGarcom = new javax.swing.JButton();
        Btn_sair = new javax.swing.JButton();
        Btn_dinheiro = new javax.swing.JButton();
        Btn_cartao = new javax.swing.JButton();
        Btn_pix = new javax.swing.JButton();
        Img_baseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Btn_chamaGarcom.setBorderPainted(false);
        Btn_chamaGarcom.setContentAreaFilled(false);
        Btn_chamaGarcom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_chamaGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_chamaGarcomActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_chamaGarcom);
        Btn_chamaGarcom.setBounds(961, 86, 40, 40);

        Btn_sair.setBorderPainted(false);
        Btn_sair.setContentAreaFilled(false);
        Btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_sair);
        Btn_sair.setBounds(880, 720, 120, 30);

        Btn_dinheiro.setBorderPainted(false);
        Btn_dinheiro.setContentAreaFilled(false);
        Btn_dinheiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_dinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_dinheiro);
        Btn_dinheiro.setBounds(40, 260, 250, 370);

        Btn_cartao.setBorderPainted(false);
        Btn_cartao.setContentAreaFilled(false);
        Btn_cartao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_cartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cartaoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_cartao);
        Btn_cartao.setBounds(380, 260, 260, 370);

        Btn_pix.setBorderPainted(false);
        Btn_pix.setContentAreaFilled(false);
        Btn_pix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_pix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_pixActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_pix);
        Btn_pix.setBounds(730, 260, 250, 370);

        Img_baseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_formaPagamento.png"))); // NOI18N
        getContentPane().add(Img_baseTela);
        Img_baseTela.setBounds(0, 0, 1020, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_chamaGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_chamaGarcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_chamaGarcomActionPerformed

    private void Btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_sairActionPerformed

    private void Btn_dinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dinheiroActionPerformed
        UI_clienteFormaPagamentoDinheiro dinheiro = new UI_clienteFormaPagamentoDinheiro();
        dinheiro.setVisible(true);
    }//GEN-LAST:event_Btn_dinheiroActionPerformed

    private void Btn_cartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cartaoActionPerformed
        UI_clienteFormaPagamentoCartao cartao = new UI_clienteFormaPagamentoCartao();
        cartao.setVisible(true);
    }//GEN-LAST:event_Btn_cartaoActionPerformed

    private void Btn_pixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_pixActionPerformed
        UI_clienteFormaPagamentoPix pix = new UI_clienteFormaPagamentoPix();
        pix.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_pixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_clienteFormaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cartao;
    private javax.swing.JButton Btn_chamaGarcom;
    private javax.swing.JButton Btn_dinheiro;
    private javax.swing.JButton Btn_pix;
    private javax.swing.JButton Btn_sair;
    private javax.swing.JLabel Img_baseTela;
    // End of variables declaration//GEN-END:variables
}
