/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

/**
 *
 * @author nicol
 */
public class UI_cadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form UI_cadastroProduto
     */
    public UI_cadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_Divisao = new javax.swing.ButtonGroup();
        Btn_Visualizar = new javax.swing.JButton();
        Btn_Enviar = new javax.swing.JButton();
        Btn_Arquivos = new javax.swing.JButton();
        Btn_Sair = new javax.swing.JButton();
        Btn_Voltar = new javax.swing.JButton();
        Sc_Categoria = new javax.swing.JComboBox<>();
        Sc_Subcategoria = new javax.swing.JComboBox<>();
        Input_Descricao = new javax.swing.JTextField();
        Input_Codigo = new javax.swing.JTextField();
        Input_Nome = new javax.swing.JTextField();
        Input_PrecoTrio = new javax.swing.JTextField();
        Input_PrecoDupla = new javax.swing.JTextField();
        Input_PrecoIndividual = new javax.swing.JTextField();
        Ck_Trio = new javax.swing.JRadioButton();
        Ck_Dupla = new javax.swing.JRadioButton();
        Ck_Individual = new javax.swing.JRadioButton();
        Img_BaseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Visualizar.setBorderPainted(false);
        Btn_Visualizar.setContentAreaFilled(false);
        getContentPane().add(Btn_Visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 50, 50));

        Btn_Enviar.setBorderPainted(false);
        Btn_Enviar.setContentAreaFilled(false);
        getContentPane().add(Btn_Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 270, 30));

        Btn_Arquivos.setBorderPainted(false);
        Btn_Arquivos.setContentAreaFilled(false);
        getContentPane().add(Btn_Arquivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 220, 40));

        Btn_Sair.setBorderPainted(false);
        Btn_Sair.setContentAreaFilled(false);
        getContentPane().add(Btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 720, 120, 30));

        Btn_Voltar.setBorderPainted(false);
        Btn_Voltar.setContentAreaFilled(false);
        getContentPane().add(Btn_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 120, 30));

        Sc_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sc_Categoria.setMaximumSize(new java.awt.Dimension(419, 42));
        Sc_Categoria.setMinimumSize(new java.awt.Dimension(419, 42));
        Sc_Categoria.setPreferredSize(new java.awt.Dimension(419, 42));
        getContentPane().add(Sc_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 430, 50));

        Sc_Subcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sc_Subcategoria.setMaximumSize(new java.awt.Dimension(419, 42));
        Sc_Subcategoria.setMinimumSize(new java.awt.Dimension(419, 42));
        Sc_Subcategoria.setPreferredSize(new java.awt.Dimension(419, 42));
        getContentPane().add(Sc_Subcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 430, 50));

        Input_Descricao.setBackground(new java.awt.Color(196, 196, 196));
        Input_Descricao.setText("jTextField1");
        Input_Descricao.setBorder(null);
        getContentPane().add(Input_Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 890, 30));

        Input_Codigo.setBackground(new java.awt.Color(196, 196, 196));
        Input_Codigo.setText("jTextField1");
        Input_Codigo.setBorder(null);
        getContentPane().add(Input_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 270, 42));

        Input_Nome.setBackground(new java.awt.Color(196, 196, 196));
        Input_Nome.setText("jTextField1");
        Input_Nome.setBorder(null);
        getContentPane().add(Input_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 440, 42));

        Input_PrecoTrio.setBackground(new java.awt.Color(196, 196, 196));
        Input_PrecoTrio.setText("jTextField1");
        Input_PrecoTrio.setBorder(null);
        getContentPane().add(Input_PrecoTrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 140, 42));

        Input_PrecoDupla.setBackground(new java.awt.Color(196, 196, 196));
        Input_PrecoDupla.setText("jTextField1");
        Input_PrecoDupla.setBorder(null);
        getContentPane().add(Input_PrecoDupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 140, 42));

        Input_PrecoIndividual.setBackground(new java.awt.Color(196, 196, 196));
        Input_PrecoIndividual.setText("jTextField1");
        Input_PrecoIndividual.setBorder(null);
        getContentPane().add(Input_PrecoIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 140, 42));

        Group_Divisao.add(Ck_Trio);
        Ck_Trio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ck_TrioActionPerformed(evt);
            }
        });
        getContentPane().add(Ck_Trio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 30, 30));

        Group_Divisao.add(Ck_Dupla);
        Ck_Dupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ck_DuplaActionPerformed(evt);
            }
        });
        getContentPane().add(Ck_Dupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 30, 30));

        Group_Divisao.add(Ck_Individual);
        Ck_Individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ck_IndividualActionPerformed(evt);
            }
        });
        getContentPane().add(Ck_Individual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 30, 30));

        Img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_CadastroProduto.png"))); // NOI18N
        getContentPane().add(Img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Ck_TrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ck_TrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ck_TrioActionPerformed

    private void Ck_IndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ck_IndividualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ck_IndividualActionPerformed

    private void Ck_DuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ck_DuplaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ck_DuplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_cadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_cadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_cadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_cadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_cadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Arquivos;
    private javax.swing.JButton Btn_Enviar;
    private javax.swing.JButton Btn_Sair;
    private javax.swing.JButton Btn_Visualizar;
    private javax.swing.JButton Btn_Voltar;
    private javax.swing.JRadioButton Ck_Dupla;
    private javax.swing.JRadioButton Ck_Individual;
    private javax.swing.JRadioButton Ck_Trio;
    private javax.swing.ButtonGroup Group_Divisao;
    private javax.swing.JLabel Img_BaseTela;
    private javax.swing.JTextField Input_Codigo;
    private javax.swing.JTextField Input_Descricao;
    private javax.swing.JTextField Input_Nome;
    private javax.swing.JTextField Input_PrecoDupla;
    private javax.swing.JTextField Input_PrecoIndividual;
    private javax.swing.JTextField Input_PrecoTrio;
    private javax.swing.JComboBox<String> Sc_Categoria;
    private javax.swing.JComboBox<String> Sc_Subcategoria;
    // End of variables declaration//GEN-END:variables
}
