/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

import Dao.Chamados_filaDAO;
import Entity.Chamados_fila;
import UI_Sistema.Modal.UI_modalChamarGarcom;

/**
 *
 * @author jessi
 */
public class UI_clienteFormaPagamentoCartao extends javax.swing.JFrame {

    /**
     * Creates new form UI_clienteMinhaConta
     */
    public UI_clienteFormaPagamentoCartao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_chamaGarcom = new javax.swing.JButton();
        Btn_sair = new javax.swing.JButton();
        Btn_voltar = new javax.swing.JButton();
        Btn_SorteioPagamentoCartao = new javax.swing.JButton();
        Input_numeros = new javax.swing.JTextField();
        Input_numeros1 = new javax.swing.JTextField();
        Input_numeros2 = new javax.swing.JTextField();
        Input_numeros3 = new javax.swing.JTextField();
        Input_nome = new javax.swing.JTextField();
        Input_validade = new javax.swing.JTextField();
        Input_cvv = new javax.swing.JTextField();
        Input_valor = new javax.swing.JTextField();
        Select_visa = new javax.swing.JCheckBox();
        Select_master = new javax.swing.JCheckBox();
        Select_elo = new javax.swing.JCheckBox();
        Select_american = new javax.swing.JCheckBox();
        Select_vr = new javax.swing.JCheckBox();
        Select_sodexo = new javax.swing.JCheckBox();
        Img_baseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Btn_chamaGarcom.setBorderPainted(false);
        Btn_chamaGarcom.setContentAreaFilled(false);
        Btn_chamaGarcom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_chamaGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_chamaGarcomActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_chamaGarcom);
        Btn_chamaGarcom.setBounds(961, 86, 50, 40);

        Btn_sair.setBorderPainted(false);
        Btn_sair.setContentAreaFilled(false);
        Btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_sair);
        Btn_sair.setBounds(880, 720, 120, 30);

        Btn_voltar.setBorderPainted(false);
        Btn_voltar.setContentAreaFilled(false);
        Btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_voltar);
        Btn_voltar.setBounds(20, 720, 110, 30);

        Btn_SorteioPagamentoCartao.setBorderPainted(false);
        Btn_SorteioPagamentoCartao.setContentAreaFilled(false);
        Btn_SorteioPagamentoCartao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_SorteioPagamentoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SorteioPagamentoCartaoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_SorteioPagamentoCartao);
        Btn_SorteioPagamentoCartao.setBounds(440, 560, 140, 40);

        Input_numeros.setBackground(new java.awt.Color(196, 196, 196));
        Input_numeros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_numeros.setText("5555");
        getContentPane().add(Input_numeros);
        Input_numeros.setBounds(230, 340, 130, 30);

        Input_numeros1.setBackground(new java.awt.Color(196, 196, 196));
        Input_numeros1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_numeros1.setText("5555");
        getContentPane().add(Input_numeros1);
        Input_numeros1.setBounds(370, 340, 130, 30);

        Input_numeros2.setBackground(new java.awt.Color(196, 196, 196));
        Input_numeros2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_numeros2.setText("5555");
        getContentPane().add(Input_numeros2);
        Input_numeros2.setBounds(510, 340, 130, 30);

        Input_numeros3.setBackground(new java.awt.Color(196, 196, 196));
        Input_numeros3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_numeros3.setText("5555");
        Input_numeros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_numeros3ActionPerformed(evt);
            }
        });
        getContentPane().add(Input_numeros3);
        Input_numeros3.setBounds(650, 340, 130, 30);

        Input_nome.setBackground(new java.awt.Color(196, 196, 196));
        Input_nome.setText("Nome impresso no cartão");
        Input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(Input_nome);
        Input_nome.setBounds(220, 420, 560, 40);

        Input_validade.setBackground(new java.awt.Color(196, 196, 196));
        Input_validade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_validade.setText("11/26");
        Input_validade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_validadeActionPerformed(evt);
            }
        });
        getContentPane().add(Input_validade);
        Input_validade.setBounds(220, 490, 140, 40);

        Input_cvv.setBackground(new java.awt.Color(196, 196, 196));
        Input_cvv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_cvv.setText("924");
        Input_cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_cvvActionPerformed(evt);
            }
        });
        getContentPane().add(Input_cvv);
        Input_cvv.setBounds(410, 490, 140, 40);

        Input_valor.setBackground(new java.awt.Color(196, 196, 196));
        Input_valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_valor.setText("92,48");
        getContentPane().add(Input_valor);
        Input_valor.setBounds(610, 490, 130, 40);
        getContentPane().add(Select_visa);
        Select_visa.setBounds(220, 250, 20, 21);

        Select_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_masterActionPerformed(evt);
            }
        });
        getContentPane().add(Select_master);
        Select_master.setBounds(310, 250, 20, 21);
        getContentPane().add(Select_elo);
        Select_elo.setBounds(400, 250, 30, 24);
        getContentPane().add(Select_american);
        Select_american.setBounds(500, 250, 30, 21);
        getContentPane().add(Select_vr);
        Select_vr.setBounds(600, 250, 21, 21);
        getContentPane().add(Select_sodexo);
        Select_sodexo.setBounds(680, 250, 20, 21);

        Img_baseTela.setBackground(new java.awt.Color(196, 196, 196));
        Img_baseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_formaPagamentoCartao.png"))); // NOI18N
        getContentPane().add(Img_baseTela);
        Img_baseTela.setBounds(0, 0, 1020, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_chamaGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_chamaGarcomActionPerformed
        Chamados_fila chamado = new Chamados_fila(0, false, 1);

        new Chamados_filaDAO().inserir(chamado);

        UI_modalChamarGarcom modal = new UI_modalChamarGarcom(this, true);
        modal.setVisible(true);
    }//GEN-LAST:event_Btn_chamaGarcomActionPerformed

    private void Btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_sairActionPerformed

    private void Btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_voltarActionPerformed
        UI_clienteFormaPagamento formaPagamento = new UI_clienteFormaPagamento();
        formaPagamento.setVisible(true);
    }//GEN-LAST:event_Btn_voltarActionPerformed

    private void Btn_SorteioPagamentoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SorteioPagamentoCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SorteioPagamentoCartaoActionPerformed

    private void Input_numeros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_numeros3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_numeros3ActionPerformed

    private void Select_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Select_masterActionPerformed

    private void Input_validadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_validadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_validadeActionPerformed

    private void Input_cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_cvvActionPerformed

    private void Input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamentoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamentoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamentoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_clienteFormaPagamentoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_clienteFormaPagamentoCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_SorteioPagamentoCartao;
    private javax.swing.JButton Btn_chamaGarcom;
    private javax.swing.JButton Btn_sair;
    private javax.swing.JButton Btn_voltar;
    private javax.swing.JLabel Img_baseTela;
    private javax.swing.JTextField Input_cvv;
    private javax.swing.JTextField Input_nome;
    private javax.swing.JTextField Input_numeros;
    private javax.swing.JTextField Input_numeros1;
    private javax.swing.JTextField Input_numeros2;
    private javax.swing.JTextField Input_numeros3;
    private javax.swing.JTextField Input_validade;
    private javax.swing.JTextField Input_valor;
    private javax.swing.JCheckBox Select_american;
    private javax.swing.JCheckBox Select_elo;
    private javax.swing.JCheckBox Select_master;
    private javax.swing.JCheckBox Select_sodexo;
    private javax.swing.JCheckBox Select_visa;
    private javax.swing.JCheckBox Select_vr;
    // End of variables declaration//GEN-END:variables
}
