/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

/**
 *
 * @author jessi
 */
public class UI_clienteBebidas extends javax.swing.JFrame {

    /**
     * Creates new form UI_clienteBebidas
     */
    public UI_clienteBebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_chamaGarcom = new javax.swing.JButton();
        Btn_bebidas = new javax.swing.JButton();
        Btn_entradas = new javax.swing.JButton();
        Btn_pratosIndividuais = new javax.swing.JButton();
        Btn_pratosCompartilhar = new javax.swing.JButton();
        Btn_sobremesa = new javax.swing.JButton();
        Btn_minhaConta = new javax.swing.JButton();
        Btn_sair = new javax.swing.JButton();
        Btn_refrigerantes = new javax.swing.JButton();
        Btn_sucos = new javax.swing.JButton();
        Btn_aguas = new javax.swing.JButton();
        Btn_cervejas = new javax.swing.JButton();
        Btn_drinks = new javax.swing.JButton();
        Img_baseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Btn_chamaGarcom.setBorderPainted(false);
        Btn_chamaGarcom.setContentAreaFilled(false);
        Btn_chamaGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_chamaGarcomActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_chamaGarcom);
        Btn_chamaGarcom.setBounds(960, 60, 50, 50);

        Btn_bebidas.setBorderPainted(false);
        Btn_bebidas.setContentAreaFilled(false);
        getContentPane().add(Btn_bebidas);
        Btn_bebidas.setBounds(20, 180, 160, 60);

        Btn_entradas.setBorderPainted(false);
        Btn_entradas.setContentAreaFilled(false);
        getContentPane().add(Btn_entradas);
        Btn_entradas.setBounds(20, 270, 160, 60);

        Btn_pratosIndividuais.setBorderPainted(false);
        Btn_pratosIndividuais.setContentAreaFilled(false);
        getContentPane().add(Btn_pratosIndividuais);
        Btn_pratosIndividuais.setBounds(20, 360, 160, 60);

        Btn_pratosCompartilhar.setBorderPainted(false);
        Btn_pratosCompartilhar.setContentAreaFilled(false);
        getContentPane().add(Btn_pratosCompartilhar);
        Btn_pratosCompartilhar.setBounds(20, 450, 160, 60);

        Btn_sobremesa.setBorderPainted(false);
        Btn_sobremesa.setContentAreaFilled(false);
        Btn_sobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sobremesaActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_sobremesa);
        Btn_sobremesa.setBounds(20, 540, 160, 60);

        Btn_minhaConta.setBorderPainted(false);
        Btn_minhaConta.setContentAreaFilled(false);
        getContentPane().add(Btn_minhaConta);
        Btn_minhaConta.setBounds(20, 630, 160, 50);

        Btn_sair.setBorderPainted(false);
        Btn_sair.setContentAreaFilled(false);
        getContentPane().add(Btn_sair);
        Btn_sair.setBounds(890, 700, 120, 30);

        Btn_refrigerantes.setBorderPainted(false);
        Btn_refrigerantes.setContentAreaFilled(false);
        getContentPane().add(Btn_refrigerantes);
        Btn_refrigerantes.setBounds(210, 150, 800, 100);

        Btn_sucos.setBorderPainted(false);
        Btn_sucos.setContentAreaFilled(false);
        getContentPane().add(Btn_sucos);
        Btn_sucos.setBounds(210, 260, 800, 100);

        Btn_aguas.setBorderPainted(false);
        Btn_aguas.setContentAreaFilled(false);
        getContentPane().add(Btn_aguas);
        Btn_aguas.setBounds(210, 370, 800, 100);

        Btn_cervejas.setBorderPainted(false);
        Btn_cervejas.setContentAreaFilled(false);
        getContentPane().add(Btn_cervejas);
        Btn_cervejas.setBounds(210, 480, 800, 90);

        Btn_drinks.setBorderPainted(false);
        Btn_drinks.setContentAreaFilled(false);
        getContentPane().add(Btn_drinks);
        Btn_drinks.setBounds(210, 590, 800, 90);

        Img_baseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_CardapioBebidas.png"))); // NOI18N
        getContentPane().add(Img_baseTela);
        Img_baseTela.setBounds(0, 0, 1025, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_chamaGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_chamaGarcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_chamaGarcomActionPerformed

    private void Btn_sobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_sobremesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_clienteBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_clienteBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_clienteBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_clienteBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_clienteBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_aguas;
    private javax.swing.JButton Btn_bebidas;
    private javax.swing.JButton Btn_cervejas;
    private javax.swing.JButton Btn_chamaGarcom;
    private javax.swing.JButton Btn_drinks;
    private javax.swing.JButton Btn_entradas;
    private javax.swing.JButton Btn_minhaConta;
    private javax.swing.JButton Btn_pratosCompartilhar;
    private javax.swing.JButton Btn_pratosIndividuais;
    private javax.swing.JButton Btn_refrigerantes;
    private javax.swing.JButton Btn_sair;
    private javax.swing.JButton Btn_sobremesa;
    private javax.swing.JButton Btn_sucos;
    private javax.swing.JLabel Img_baseTela;
    // End of variables declaration//GEN-END:variables
}
