/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

/**
 *
 * @author nicol
 */
public class UI_GarcomMesas extends javax.swing.JFrame {

    /**
     * Creates new form UI_GarcomMesas
     */
    public UI_GarcomMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Receber = new javax.swing.JButton();
        Btn_Ativar = new javax.swing.JButton();
        Btn_Voltar = new javax.swing.JButton();
        Btn_Sair = new javax.swing.JButton();
        Painel_Status = new javax.swing.JPanel();
        Txt_Status = new javax.swing.JLabel();
        Painel_Situacao = new javax.swing.JPanel();
        Txt_Situacao = new javax.swing.JLabel();
        Txt_ValorSituacao = new javax.swing.JLabel();
        Painel_ValorTotal = new javax.swing.JPanel();
        Txt_ValorTotal = new javax.swing.JLabel();
        Txt_Valor = new javax.swing.JLabel();
        Painel_ValorAberto = new javax.swing.JPanel();
        Txt_ValorAbertoTotal = new javax.swing.JLabel();
        Txt_ValorAbTotal = new javax.swing.JLabel();
        Painel_Subcontas = new javax.swing.JPanel();
        Txt_Subcontas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Img_BaseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Receber.setBorderPainted(false);
        Btn_Receber.setContentAreaFilled(false);
        Btn_Receber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Receber, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 80, 130));

        Btn_Ativar.setBorderPainted(false);
        Btn_Ativar.setContentAreaFilled(false);
        Btn_Ativar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Ativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 80, 80));

        Btn_Voltar.setBorderPainted(false);
        Btn_Voltar.setContentAreaFilled(false);
        Btn_Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 120, 40));

        Btn_Sair.setBorderPainted(false);
        Btn_Sair.setContentAreaFilled(false);
        Btn_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 720, 120, 30));

        Painel_Status.setBackground(new java.awt.Color(255, 255, 255));
        Painel_Status.setMaximumSize(new java.awt.Dimension(590, 40));
        Painel_Status.setMinimumSize(new java.awt.Dimension(590, 40));
        Painel_Status.setRequestFocusEnabled(false);

        Txt_Status.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Txt_Status.setText("Status");

        javax.swing.GroupLayout Painel_StatusLayout = new javax.swing.GroupLayout(Painel_Status);
        Painel_Status.setLayout(Painel_StatusLayout);
        Painel_StatusLayout.setHorizontalGroup(
            Painel_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Status)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        Painel_StatusLayout.setVerticalGroup(
            Painel_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_StatusLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(Txt_Status)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(Painel_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        Painel_Situacao.setBackground(new java.awt.Color(242, 242, 235));
        Painel_Situacao.setMaximumSize(new java.awt.Dimension(590, 40));
        Painel_Situacao.setMinimumSize(new java.awt.Dimension(590, 40));
        Painel_Situacao.setPreferredSize(new java.awt.Dimension(590, 40));

        Txt_Situacao.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Txt_Situacao.setText("Situação: ");

        Txt_ValorSituacao.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        javax.swing.GroupLayout Painel_SituacaoLayout = new javax.swing.GroupLayout(Painel_Situacao);
        Painel_Situacao.setLayout(Painel_SituacaoLayout);
        Painel_SituacaoLayout.setHorizontalGroup(
            Painel_SituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_SituacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Situacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_ValorSituacao)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        Painel_SituacaoLayout.setVerticalGroup(
            Painel_SituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_SituacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_SituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Situacao)
                    .addComponent(Txt_ValorSituacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Painel_Situacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 590, 40));

        Painel_ValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        Painel_ValorTotal.setMaximumSize(new java.awt.Dimension(590, 40));
        Painel_ValorTotal.setMinimumSize(new java.awt.Dimension(590, 40));
        Painel_ValorTotal.setPreferredSize(new java.awt.Dimension(590, 40));
        Painel_ValorTotal.setRequestFocusEnabled(false);

        Txt_ValorTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Txt_ValorTotal.setText("Valor Total:");

        Txt_Valor.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        javax.swing.GroupLayout Painel_ValorTotalLayout = new javax.swing.GroupLayout(Painel_ValorTotal);
        Painel_ValorTotal.setLayout(Painel_ValorTotalLayout);
        Painel_ValorTotalLayout.setHorizontalGroup(
            Painel_ValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_ValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_Valor)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        Painel_ValorTotalLayout.setVerticalGroup(
            Painel_ValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_ValorTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_ValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_ValorTotal)
                    .addComponent(Txt_Valor))
                .addContainerGap())
        );

        getContentPane().add(Painel_ValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        Painel_ValorAberto.setBackground(new java.awt.Color(242, 242, 235));
        Painel_ValorAberto.setMaximumSize(new java.awt.Dimension(590, 40));
        Painel_ValorAberto.setMinimumSize(new java.awt.Dimension(590, 40));
        Painel_ValorAberto.setPreferredSize(new java.awt.Dimension(590, 40));
        Painel_ValorAberto.setRequestFocusEnabled(false);

        Txt_ValorAbertoTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Txt_ValorAbertoTotal.setText("Valor em aberto Total:");

        Txt_ValorAbTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        javax.swing.GroupLayout Painel_ValorAbertoLayout = new javax.swing.GroupLayout(Painel_ValorAberto);
        Painel_ValorAberto.setLayout(Painel_ValorAbertoLayout);
        Painel_ValorAbertoLayout.setHorizontalGroup(
            Painel_ValorAbertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ValorAbertoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_ValorAbertoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_ValorAbTotal)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        Painel_ValorAbertoLayout.setVerticalGroup(
            Painel_ValorAbertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_ValorAbertoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_ValorAbertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_ValorAbertoTotal)
                    .addComponent(Txt_ValorAbTotal))
                .addContainerGap())
        );

        getContentPane().add(Painel_ValorAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        Painel_Subcontas.setBackground(new java.awt.Color(255, 255, 255));
        Painel_Subcontas.setMaximumSize(new java.awt.Dimension(590, 40));
        Painel_Subcontas.setMinimumSize(new java.awt.Dimension(590, 40));
        Painel_Subcontas.setPreferredSize(new java.awt.Dimension(590, 40));
        Painel_Subcontas.setRequestFocusEnabled(false);

        Txt_Subcontas.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Txt_Subcontas.setText("Subcontas:");

        javax.swing.GroupLayout Painel_SubcontasLayout = new javax.swing.GroupLayout(Painel_Subcontas);
        Painel_Subcontas.setLayout(Painel_SubcontasLayout);
        Painel_SubcontasLayout.setHorizontalGroup(
            Painel_SubcontasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_SubcontasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Subcontas)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        Painel_SubcontasLayout.setVerticalGroup(
            Painel_SubcontasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_SubcontasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Subcontas)
                .addContainerGap())
        );

        getContentPane().add(Painel_Subcontas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Título 2", "Título 3"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 490, 230));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, 360));

        Img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_GarcomMesas.png"))); // NOI18N
        getContentPane().add(Img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_GarcomMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_GarcomMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_GarcomMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_GarcomMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_GarcomMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ativar;
    private javax.swing.JButton Btn_Receber;
    private javax.swing.JButton Btn_Sair;
    private javax.swing.JButton Btn_Voltar;
    private javax.swing.JLabel Img_BaseTela;
    private javax.swing.JPanel Painel_Situacao;
    private javax.swing.JPanel Painel_Status;
    private javax.swing.JPanel Painel_Subcontas;
    private javax.swing.JPanel Painel_ValorAberto;
    private javax.swing.JPanel Painel_ValorTotal;
    private javax.swing.JLabel Txt_Situacao;
    private javax.swing.JLabel Txt_Status;
    private javax.swing.JLabel Txt_Subcontas;
    private javax.swing.JLabel Txt_Valor;
    private javax.swing.JLabel Txt_ValorAbTotal;
    private javax.swing.JLabel Txt_ValorAbertoTotal;
    private javax.swing.JLabel Txt_ValorSituacao;
    private javax.swing.JLabel Txt_ValorTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
