/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

/**
 *
 * @author nicol
 */
public class UI_garcomTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UI_GarcomTelaPrincipal
     */
    public UI_garcomTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Mesas = new javax.swing.JButton();
        Btn_Sair = new javax.swing.JButton();
        Btn_Chamados = new javax.swing.JButton();
        img_BaseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Mesas.setBorderPainted(false);
        Btn_Mesas.setContentAreaFilled(false);
        Btn_Mesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 260, 370));

        Btn_Sair.setBorderPainted(false);
        Btn_Sair.setContentAreaFilled(false);
        Btn_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SairActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, 120, 30));

        Btn_Chamados.setBorderPainted(false);
        Btn_Chamados.setContentAreaFilled(false);
        Btn_Chamados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Chamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChamadosActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Chamados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 260, 370));

        img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_MenuGarcom.png"))); // NOI18N
        getContentPane().add(img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SairActionPerformed

    private void Btn_ChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChamadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ChamadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_garcomTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_garcomTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_garcomTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_garcomTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_garcomTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Chamados;
    private javax.swing.JButton Btn_Mesas;
    private javax.swing.JButton Btn_Sair;
    private javax.swing.JLabel img_BaseTela;
    // End of variables declaration//GEN-END:variables
}
