/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema;

import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class UI_loading extends javax.swing.JFrame {

    /**
     * Creates new form UI_loading
     */
    public UI_loading() {
        initComponents();
        
        new  Thread(){
            
         public void run(){
             try {      
                for(int i = 0; i <= 100;  i += 2){
                    sleep(100);

                    BarraProgresso.setValue(i);
                }
                
                dispose();
                
            }catch(InterruptedException e){
                JOptionPane.showConfirmDialog(null, "Erro!");
            }
         }  
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraProgresso = new javax.swing.JProgressBar();
        img_Loading = new javax.swing.JLabel();
        Img_BaseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 535));
        setMinimumSize(new java.awt.Dimension(930, 535));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraProgresso.setBackground(new java.awt.Color(241, 241, 241));
        BarraProgresso.setForeground(new java.awt.Color(141, 11, 0));
        BarraProgresso.setMaximumSize(new java.awt.Dimension(727, 73));
        BarraProgresso.setMinimumSize(new java.awt.Dimension(727, 73));
        BarraProgresso.setName(""); // NOI18N
        BarraProgresso.setPreferredSize(new java.awt.Dimension(727, 73));
        getContentPane().add(BarraProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        img_Loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Gif_Loading.gif"))); // NOI18N
        getContentPane().add(img_Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        Img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_backgroundLoading.png"))); // NOI18N
        getContentPane().add(Img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgresso;
    private javax.swing.JLabel Img_BaseTela;
    private javax.swing.JLabel img_Loading;
    // End of variables declaration//GEN-END:variables
}
