/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema.Modal;

/**
 *
 * @author nicol
 */
public class UI_ModalConfirmarPedidoCompartilhado extends javax.swing.JDialog {

    /**
     * Creates new form UI_ModalAddItemCarrinho
     */
    public UI_ModalConfirmarPedidoCompartilhado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Adicionar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Txt_QtdPessoa = new javax.swing.JLabel();
        Txt_NomeProduto = new javax.swing.JLabel();
        Txt_ValorItemPorPessoa = new javax.swing.JLabel();
        Txt_ValorItem = new javax.swing.JLabel();
        Img_Produto = new javax.swing.JLabel();
        Img_BaseTela = new javax.swing.JLabel();
        Txt_QtdItem1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Adicionar.setBorderPainted(false);
        Btn_Adicionar.setContentAreaFilled(false);
        Btn_Adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        Btn_Cancelar.setBorderPainted(false);
        Btn_Cancelar.setContentAreaFilled(false);
        Btn_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, 30));

        Txt_QtdPessoa.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        Txt_QtdPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_QtdPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 40, 30));

        Txt_NomeProduto.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        getContentPane().add(Txt_NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 250, 20));

        Txt_ValorItemPorPessoa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Txt_ValorItemPorPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_ValorItemPorPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, 20));

        Txt_ValorItem.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Txt_ValorItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_ValorItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, 20));
        getContentPane().add(Img_Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 90));

        Img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_ModalConfirmarPedidoCompartilhado.png"))); // NOI18N
        getContentPane().add(Img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Txt_QtdItem1.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        Txt_QtdItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_QtdItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoCompartilhado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoCompartilhado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoCompartilhado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoCompartilhado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI_ModalConfirmarPedidoCompartilhado dialog = new UI_ModalConfirmarPedidoCompartilhado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Adicionar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JLabel Img_BaseTela;
    private javax.swing.JLabel Img_Produto;
    private javax.swing.JLabel Txt_NomeProduto;
    private javax.swing.JLabel Txt_QtdItem1;
    private javax.swing.JLabel Txt_QtdPessoa;
    private javax.swing.JLabel Txt_ValorItem;
    private javax.swing.JLabel Txt_ValorItemPorPessoa;
    // End of variables declaration//GEN-END:variables
}
