/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Sistema.Modal;

/**
 *
 * @author nicol
 */
public class UI_ModalConfirmarPedidoIndividual extends javax.swing.JDialog {

    /**
     * Creates new form UI_ModalAddItemCarrinho
     */
    public UI_ModalConfirmarPedidoIndividual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Confirmar = new javax.swing.JButton();
        Btn_cancelar = new javax.swing.JButton();
        Txt_QtdItem = new javax.swing.JLabel();
        Txt_NomeProduto = new javax.swing.JLabel();
        Txt_ValorItem = new javax.swing.JLabel();
        Img_Produto = new javax.swing.JLabel();
        Img_BaseTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Confirmar.setBorderPainted(false);
        Btn_Confirmar.setContentAreaFilled(false);
        Btn_Confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        Btn_cancelar.setBorderPainted(false);
        Btn_cancelar.setContentAreaFilled(false);
        Btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, 30));

        Txt_QtdItem.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        Txt_QtdItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_QtdItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, 30));

        Txt_NomeProduto.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        getContentPane().add(Txt_NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 250, 20));

        Txt_ValorItem.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Txt_ValorItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Txt_ValorItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 100, 20));
        getContentPane().add(Img_Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 90));

        Img_BaseTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img_ModalConfirmarPedidoIndividual.png"))); // NOI18N
        getContentPane().add(Img_BaseTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ModalConfirmarPedidoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI_ModalConfirmarPedidoIndividual dialog = new UI_ModalConfirmarPedidoIndividual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Confirmar;
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JLabel Img_BaseTela;
    private javax.swing.JLabel Img_Produto;
    private javax.swing.JLabel Txt_NomeProduto;
    private javax.swing.JLabel Txt_QtdItem;
    private javax.swing.JLabel Txt_ValorItem;
    // End of variables declaration//GEN-END:variables
}
